/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { State } from "./components/meowsona-head/meowsona-head";
export { State } from "./components/meowsona-head/meowsona-head";
export namespace Components {
    interface MeowsonaHead {
        "atlasUrl": string;
        /**
          * @default 128
         */
        "size": number;
        /**
          * @default 'idle'
         */
        "state": State;
    }
}
declare global {
    interface HTMLMeowsonaHeadElement extends Components.MeowsonaHead, HTMLStencilElement {
    }
    var HTMLMeowsonaHeadElement: {
        prototype: HTMLMeowsonaHeadElement;
        new (): HTMLMeowsonaHeadElement;
    };
    interface HTMLElementTagNameMap {
        "meowsona-head": HTMLMeowsonaHeadElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface MeowsonaHead {
        "atlasUrl": string;
        /**
          * @default 128
         */
        "size"?: number;
        /**
          * @default 'idle'
         */
        "state"?: State;
    }

    interface MeowsonaHeadAttributes {
        "state": State;
        "atlasUrl": string;
        "size": number;
    }

    interface IntrinsicElements {
        "meowsona-head": Omit<MeowsonaHead, keyof MeowsonaHeadAttributes> & { [K in keyof MeowsonaHead & keyof MeowsonaHeadAttributes]?: MeowsonaHead[K] } & { [K in keyof MeowsonaHead & keyof MeowsonaHeadAttributes as `attr:${K}`]?: MeowsonaHeadAttributes[K] } & { [K in keyof MeowsonaHead & keyof MeowsonaHeadAttributes as `prop:${K}`]?: MeowsonaHead[K] } & OneOf<"atlasUrl", MeowsonaHead["atlasUrl"], MeowsonaHeadAttributes["atlasUrl"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "meowsona-head": LocalJSX.IntrinsicElements["meowsona-head"] & JSXBase.HTMLAttributes<HTMLMeowsonaHeadElement>;
        }
    }
}
